# This composite action is created to encapsulate common steps for running audit, linting, and testing
# of changed packages. It is utilized across multiple workflows to minimize duplication.
# For more details on creating composite actions, refer to:
# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action

name: "Validate"
description: "Run audit, lint, and tests for changed packages"
inputs:
  after:
    description: The SHA of the HEAD commit.
    required: true
  before:
    description: The SHA of the commit before changes were made.
    required: true
runs:
  using: "composite"
  steps:
    - name: Run tests
      run: |
        # Extract packages
        PACKAGES=($(find packages -mindepth 1 -maxdepth 1 -type d | sort -u))
        echo "Packages: $PACKAGES"

        # Extract changed directories
        CHANGED_DIRS=($(git diff --name-only ${{ inputs.after }} ${{ inputs.before }} | awk -F/ '/\// {print $1}' | sort -u))
        echo "Changed directories: $CHANGED_DIRS"

        # Validate changed packages
        for PACKAGE in "$PACKAGES[@]"; do
          if [[ " ${CHANGED_DIRS[*]} " =~ [[:space:]]${PACKAGE}[[:space:]] ]]; then
            pnpm run test --if-present
            echo "Validated package: $PACKAGE"
          fi
        done
      shell: bash
