# This composite action is created to encapsulate common steps for running audit, linting, and testing
# of changed packages. It is utilized across multiple workflows to minimize duplication.
# For more details on creating composite actions, refer to:
# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action

name: "Validate"
description: "Run audit, lint, and tests for changed packages"
inputs:
  after:
    description: The SHA of the HEAD commit.
    required: true
  before:
    description: The SHA of the commit before changes were made.
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: "https://npm.pkg.github.com"
    - name: Run tests
      run: |
        # Extract workspaces
        WORKSPACES=($(jq -r '.workspaces[]' package.json | sort -u))
        echo "NPM workspaces: $WORKSPACES"

        # Extract changed directories
        CHANGED_DIRS=($(git diff --name-only ${{ inputs.after }} ${{ inputs.before }} | awk -F/ '/\// {print $1}' | sort -u))
        echo "Changed directories: $CHANGED_DIRS"

        # Validate changed workspaces
        for WORKSPACE in "$WORKSPACES[@]"; do
          if [[ " ${CHANGED_DIRS[*]} " =~ [[:space:]]${WORKSPACE}[[:space:]] ]]; then
            npm ci -w $WORKSPACE
            npm run test -w $WORKSPACE
          fi
        done
      shell: bash
