# This composite action is created to encapsulate common steps for running audit, linting, and testing
# of changed packages. It is utilized across multiple workflows to minimize duplication.
# For more details on creating composite actions, refer to:
# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action

name: "Validate"
description: "Run audit, lint, and tests for changed packages"
inputs:
  after:
    description: The SHA of the HEAD commit.
    required: true
  before:
    description: The SHA of the commit before changes were made.
    required: true
runs:
  using: "composite"
  steps:
    - name: Run tests
      run: |
        CHANGED_DIRS=$(git diff --name-only ${{ inputs.after }} ${{ inputs.before }} | awk -F/ '{if (NF>1) print $1"/"$2}' | sort -u)
        PACKAGES=$(find packages -mindepth 1 -maxdepth 1 -type d | sort -u)
        for PACKAGE in $PACKAGES
        do
          for CHANGED_DIR in $CHANGED_DIRS
          do
            if [ "$PACKAGE" = "$CHANGED_DIR" ]
            then
              pnpm run --if-present --filter="$PACKAGE" test
              echo "Validated package: $PACKAGE"
            fi
          done
        done
      shell: bash
