# This composite action is created to encapsulate common steps for running audit, linting, and testing
# of changed packages. It is utilized across multiple workflows to minimize duplication.
# For more details on creating composite actions, refer to:
# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action

name: "Validate"
description: "Run audit, lint, and tests for changed packages"
inputs:
  after:
    required: true
  before:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: "https://npm.pkg.github.com"
    - name: Run tests
      run: |
        # Get the list of changed files between commits
        CHANGED_FILES=$(git diff --name-only ${{ inputs.after }} ${{ inputs.before }})
        echo "Changed files:"
        echo "$CHANGED_FILES"

        # Extract unique package names from the changed files
        CHANGED_PACKAGES=$(echo "$CHANGED_FILES" | grep -E '^(multiply|sum|difference)/' || true | cut -d/ -f1 | sort | uniq | tr '\n' ' ')
        echo "Changed packages:"
        echo "$CHANGED_PACKAGES"

        # If no packages were changed, skip the validation
        if [ -z "$CHANGED_PACKAGES" ]; then
          echo "No changed packages. Skipping tests."
          exit 0
        fi

        # Validate each changed package
        for PACKAGE in $CHANGED_PACKAGES; do
          npm ci -w $PACKAGE
          npm run test -w $PACKAGE
        done
      shell: bash
