name: "Publish"
description: "Publish Package to GitHub registry"
inputs:
  package:
    description: Package to publish
    required: true
  ref:
    description: action/checkout@v4 ref
    required: true
  node-auth-token:
    description: Token to publish package to GitHub NPM package repository
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Build
      run: pnpm run --filter=${{ inputs.package }} build
      shell: bash
    - name: Publish
      run: pnpm publish --filter=${{ inputs.package }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
      shell: bash
