name: prerelease-please

on:
  push:
    branches: ["pre/*"]

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          target-branch: ${{ github.ref_name }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: "https://npm.pkg.github.com"
        # Bug: Using "if: ${{ steps.release.outputs.releases_created }}" doesn't work as expected.
        # Workaround: Use "if: ${{ steps.release.outputs.releases_created == 'true' }}" instead.
        # See issue: https://github.com/googleapis/release-please-action/issues/912
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - name: Publish multiply package
        uses: ./.github/actions/publish
        with:
          workspace: multiply
          ref: ${{ steps.release.output['multiply--tag_name'] }}
          node-auth-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs['multiply--release_created'] }}
      - name: Publish sum package
        uses: ./.github/actions/publish
        with:
          workspace: sum
          ref: ${{ steps.release.output['sum--tag_name'] }}
          node-auth-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs['sum--release_created'] }}
      - name: Publish difference package
        uses: ./.github/actions/publish
        with:
          workspace: difference
          ref: ${{ steps.release.output['difference--tag_name'] }}
          node-auth-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs['difference--release_created'] }}
