name: prerelease-please

on:
  push:
    branches: ["pre/*"]

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # The default fetch-depth is 1, which retrieves only the latest commit and lacks history, breaking the git diff command.
          # Instead of implementing complex logic to calculate the required commit history, we fetch a fixed number of commits.
          # Fetching 100 commits is sufficient since commits to the main branch are usually squashed into a single commit.
          fetch-depth: 100
      # Fetch the latest commit hash of the main branch to compare with the prerelease branch
      # and determine which services have changed for validation purposes.
      - name: Get main branch commit SHA
        id: get_main_sha
        run: |
          git fetch origin main:refs/remotes/origin/main
          echo "commit-sha=$(git rev-parse origin/main)" >> "$GITHUB_OUTPUT"
      - name: Validate
        uses: ./.github/actions/validate
        with:
          before: ${{ steps.get_main_sha.outputs.commit-sha }}
          after: ${{ github.event.after }}
      - name: Release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          target-branch: ${{ github.ref_name }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: "https://npm.pkg.github.com"
        # Bug: Using "if: ${{ steps.release.outputs.releases_created }}" doesn't work as expected.
        # Workaround: Use "if: ${{ steps.release.outputs.releases_created == 'true' }}" instead.
        # See issue: https://github.com/googleapis/release-please-action/issues/912
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Publish multiply package
        uses: ./.github/actions/publish
        with:
          package: packages/multiply
          ref: ${{ steps.release.output['packages/multiply--tag_name'] }}
          node-auth-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs['packages/multiply--release_created'] }}
      - name: Publish sum package
        uses: ./.github/actions/publish
        with:
          package: packages/sum
          ref: ${{ steps.release.output['packages/sum--tag_name'] }}
          node-auth-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs['packages/sum--release_created'] }}
      - name: Publish difference package
        uses: ./.github/actions/publish
        with:
          package: packages/difference
          ref: ${{ steps.release.output['packages/difference--tag_name'] }}
          node-auth-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs['packages/difference--release_created'] }}
