name: pull-request

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get changed packages
        id: changed
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Changed files: $CHANGED_FILES"
          CHANGED_PACKAGES=$(echo "$CHANGED_FILES" | grep -E '^packages/[^/]+/' | cut -d/ -f2 | sort | uniq)
          echo "Changed packages: $CHANGED_PACKAGES"
          echo "changed_packages=$CHANGED_PACKAGES" >> $GITHUB_ENV

      - name: Run tests for changed packages
        run: |
          for PACKAGE in $CHANGED_PACKAGES; do
            echo "Running tests for package: $PACKAGE"
            cd packages/$PACKAGE
            npm run test
            cd -
          done
        env:
          CHANGED_PACKAGES: ${{ env.changed_packages }}