name: pull-request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
      - .github/workflows/pull-request.yml

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Needed for the git diff command
          # For more information, see https://stackoverflow.com/questions/71204693/git-diff-not-working-on-github-actions-fatal-bad-object-7100c3bbc34a9667ca9034.
          fetch-depth: $(($COMMIT_COUNT+1))
        env:
          COMMIT_COUNT: ${{ github.event.pull_request.commits}}
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          CHANGED_PACKAGES=$(echo "$CHANGED_FILES" | grep -E '^packages/[^/]+/' | cut -d/ -f2 | sort | uniq | tr '\n' ' ')
          if [ -z "$CHANGED_PACKAGES" ]; then
            echo "No changed packages. Skipping tests."
            exit 0
          fi
          for PACKAGE in $CHANGED_PACKAGES; do
            cd packages/$PACKAGE
            npm run test
            cd -
          done