name: release-please

on:
  push:
    branches: [ "main" ]

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jmaver-plume'
        if: ${{ steps.release.outputs.releases_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.releases_created }}
      - run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          CHANGED_PACKAGES=$(echo "$CHANGED_FILES" | grep -E '^packages/[^/]+/' | cut -d/ -f2 | sort | uniq | tr '\n' ' ')
          if [ -z "$CHANGED_PACKAGES" ]; then
            echo "No changed packages. Skipping tests."
            exit 0
          fi
          for PACKAGE in $CHANGED_PACKAGES; do
            cd packages/$PACKAGE
            npm run test
            cd -
          done
        if: ${{ steps.release.outputs.releases_created }}
      - run: npm publish --workspace packages/multiply
        if: ${{ steps.release.outputs['packages/multiply--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --workspace packages/sum
        if: ${{ steps.release.outputs['packages/sum--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
