name: release-please

on:
  push:
    branches: ["main"]

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # The default fetch-depth is 1, which retrieves only the latest commit and lacks history, breaking the git diff command.
          # Instead of implementing complex logic to calculate the required commit history, we fetch a fixed number of commits.
          # Fetching 10 commits is sufficient since commits to the main branch are usually squashed into a single commit.
          fetch-depth: 10
      - name: Validate
        uses: ./.github/actions/validate/action.yml
        with:
          before: ${{ github.event.before }}
          after: ${{ github.event.after }}
      - name: Release
        uses: googleapis/release-please-action@v4
        id: release
      - name: Checkout code
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: "https://npm.pkg.github.com"
        if: ${{ steps.release.outputs.releases_created }}
      - name: Install dependencies
        run: npm ci
        if: ${{ steps.release.outputs.releases_created }}
      - name: Publish multiply package
        run: npm publish --workspace multiply
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs['multiply--release_created'] }}
      - name: Publish sum package
        run: |
          npm run build --workspace sum
          npm publish --workspace sum
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs['sum--release_created'] }}
      - name: Publish difference package
        run: npm publish --workspace difference
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs['difference--release_created'] }}
