name: release-please

on:
  push:
    branches: [ "main" ]

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_PAT_TOKEN }}
      - run: npm publish --workspace packages/multiply
        if: ${{ steps.release.outputs['packages/multiply--release_created'] }}
      - run: npm publish --workspace packages/sum
        if: ${{ steps.release.outputs['packages/sum--release_created'] }}
